<?php
session_start();
include("db.php");
include("session_check.php");

if($_SESSION['role'] != 'admin'){
    header("Location: login.php");
    exit();
}

if(!isset($_SESSION['report_preview'])){
    header("Location: generate_reports.php");
    exit();
}

require __DIR__ . '/vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

$preview = $_SESSION['report_preview'];
$sql = $preview['sql'];
$report = $preview['report'];
$columns = $preview['columns'];

$result = mysqli_query($conn, $sql);
$rows = [];

if($result){
    while($row = mysqli_fetch_assoc($result)){
        $rows[] = $row;
    }
}

$title = "Report Preview Export";
if($report == 'traffic') $title = "Traffic Logs Report";
if($report == 'blocked') $title = "Blocked Sites Report";
if($report == 'alerts') $title = "Alert / Notification Logs Report";
if($report == 'support') $title = "Support Issues Report";
if($report == 'users') $title = "Users Report";

$logoPath = __DIR__ . "/images/logo.png";
$logoSrc = "";
if(file_exists($logoPath)){
    $logoData = base64_encode(file_get_contents($logoPath));
    $logoSrc = "data:image/png;base64," . $logoData;
}

$html = '
<html>
<head>
<style>

@page {
    margin: 140px 40px 90px 40px;
}

body{
    font-family: DejaVu Sans, Arial, sans-serif;
    font-size: 12px;
    margin: 0;
    padding: 0;
}

.header{
    position: fixed;
    top: -110px;
    left: 0;
    right: 0;
    height: 90px;
    text-align: center;
}

.header img{
    width: 60px;
    display:block;
    margin: 0 auto 5px auto;
}

.header h3{
    margin: 0;
    font-size: 18px;
}

.report-meta{
    text-align:center;
    margin-bottom: 20px;
}

.footer{
    position: fixed;
    bottom: -55px;
    left: 0;
    right: 0;
    text-align: center;
    font-size: 11px;
    color: #555;
}

h1{
    text-align:center;
    margin: 0 0 20px 0;
    font-size: 24px;
}

h2{
    background:#eaeaea;
    padding:8px;
    margin-top:25px;
    margin-bottom:10px;
    font-size:18px;
}

table{
    width:100%;
    border-collapse:collapse;
    margin-top:10px;
    margin-bottom:25px;
    font-size:11px;
}

th{
    background:#f2f2f2;
}

td, th{
    border:1px solid #000;
    padding:6px;
    text-align:center;
    vertical-align:middle;
    word-wrap:break-word;
}

p{
    margin: 5px 0;
}

</style>
</head>

<body>

<div class="header">';
if($logoSrc != ""){
    $html .= '<img src="'.$logoSrc.'">';
}
$html .= '
    <h3>SKBB WiFi Security System</h3>
</div>

<div class="footer">
    © 2026 Sekolah Kebangsaan Batu Belah
</div>

<h1>Security Report</h1>

<div class="report-meta">
    <p><b>Generated by:</b> '.htmlspecialchars($_SESSION['name']).'</p>
    <p><b>Date:</b> '.date("Y-m-d H:i:s").'</p>
</div>
';

if(empty($rows)){
    $html .= '<p>No data available.</p>';
} else {
    $html .= '<table><tr><th>No.</th>';
    foreach($columns as $col){
        $html .= '<th>'.htmlspecialchars($col).'</th>';
    }
    $html .= '</tr>';

    $no = 1;
    foreach($rows as $row){
        $html .= '<tr><td>'.$no++.'</td>';
        foreach($columns as $col){
            $html .= '<td>'.htmlspecialchars((string)($row[$col] ?? '')).'</td>';
        }
        $html .= '</tr>';
    }

    $html .= '</table>';
}

$html .= '</body></html>';

/* =========================
   GENERATE PDF
========================= */

$options = new Options();
$options->set('isRemoteEnabled', true);
$options->set('isHtml5ParserEnabled', true);

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

header("Content-Type: application/pdf");
header("Content-Disposition: attachment; filename=skbb_report_".date("Ymd_His").".pdf");

echo $dompdf->output();
exit();
?>
